open_fit:
	/bin/python3 "/home/bernardo/Scrivania/FISICA/ASTROFISICA/&Argomenti/Filaments/MBM40/open_fit.py" > results.txt

add_info:
	/bin/python3 "/home/bernardo/Scrivania/FISICA/ASTROFISICA/&Argomenti/Filaments/MBM40/open_fit.py" >> results.txt